apiVersion: apps/v1
kind: Deployment
metadata:
  name: trading-psql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trading-psql
  template:
    metadata:
      labels:
        app: trading-psql
    spec:
      containers:
      - name: postgres
        image: jasdhillon152/trading-psql:latest  
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: psql-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: psql-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: psql-secret
              key: POSTGRES_DB
        volumeMounts:
        - name: psql-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: psql-storage
        persistentVolumeClaim:
          claimName: psql-pvc
