apiVersion: v1
kind: Service
metadata:
  name: trading-app-service
spec:
  selector:
    app: trading-app           
  ports:
    - protocol: TCP
      port: 80                  
      targetPort: 8080          
  type: LoadBalancer           
